package jmc.skweb.core.model;



// Generated 23/09/2011 12:11:03 by Hibernate Tools 3.2.0.b9

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Gente generated by hbm2java
 */
@Entity
@Table(name = "EmpresaWeb", schema = "ComunSql")
public class EmpresaWeb implements java.io.Serializable {

	private Integer idEmpresaWeb;	
	private String nombre;
	private Integer empresaNrSk;
	private String usrPami;
	private String passPami;
	private String gln;
	private Integer tipoEmpresa;
	private String urlTraza;
	
	@Id
	public Integer getIdEmpresaWeb() {
		return idEmpresaWeb;
	}
	public void setIdEmpresaWeb(Integer idEmpresaWeb) {
		this.idEmpresaWeb = idEmpresaWeb;
	}
	public String getNombre() {
		return nombre;
	}
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	public Integer getEmpresaNrSk() {
		return empresaNrSk;
	}
	public void setEmpresaNrSk(Integer empresaNrSk) {
		this.empresaNrSk = empresaNrSk;
	}
	public String getUsrPami() {
		return usrPami;
	}
	public void setUsrPami(String usrPami) {
		this.usrPami = usrPami;
	}
	public String getPassPami() {
		return passPami;
	}
	public void setPassPami(String passPami) {
		this.passPami = passPami;
	}
	public String getGln() {
		return gln;
	}
	public void setGln(String gln) {
		this.gln = gln;
	}
	public Integer getTipoEmpresa() {
		return tipoEmpresa;
	}
	public void setTipoEmpresa(Integer tipoEmpresa) {
		this.tipoEmpresa = tipoEmpresa;
	}
	public String getUrlTraza() {
		return urlTraza;
	}
	public void setUrlTraza(String urlTraza) {
		this.urlTraza = urlTraza;
	}
	
}

