package jmc.skweb.core.model;

// Generated 22/09/2011 00:18:30 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Immutable;

import jmc.skweb.util.DateUtil;
import jmc.skweb.util.FormatUtil;
import jmc.skweb.util.MathUtil;

/**
 * Transac generated by hbm2java
 */
@Entity
@Table(name = "TransacRecibidaFarma", schema = "")
public class TransacRecibidaFarma implements java.io.Serializable {
	
	
	private Integer transacNr;
	private EmpresaWeb empresaWeb;
	private Timestamp fecha;
	
	@Id
	public Integer getTransacNr() {
		return transacNr;
	}
	public void setTransacNr(Integer transacNr) {
		this.transacNr = transacNr;
	}
	
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEmpresaWeb")
	public EmpresaWeb getEmpresaWeb() {
		return empresaWeb;
	}
	public void setEmpresaWeb(EmpresaWeb empresaWeb) {
		this.empresaWeb = empresaWeb;
	}
	
	public Timestamp getFecha() {
		return fecha;
	}
	public void setFecha(Timestamp fecha) {
		this.fecha = fecha;
	}

	


}
