package jmc.skweb.core.model.traza;

// Generated 08/05/2012 00:04:43 by Hibernate Tools 3.2.0.b9

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import jmc.skweb.core.model.Stock;

import com.google.gson.annotations.Expose;

/**
 * Trazabi generated by hbm2java
 */
@Entity
@Table(name = "TrazabiFarma", schema = "Farmacias.dbo")
public class TrazabiFarma implements java.io.Serializable {

	private Integer nr;
	private Stock stockTmp;
	
	private Stock stock;
	private String gtin = "";
	private String serieGtin;
	private Float cant;
	private Integer exinr;
	private String nrlote;
	private String nrFacCompra;
	private String nrRemCompra;
	private Integer genteNr;
	private String vencimLote;
	private Integer tipoIng;
	private Integer tipoSalida;
	private Integer impreso;
	private Integer unico;
	private Integer sucursal;
	private Integer codEventoIng;
	private Date fechaIng;
	private String glnorigenIng;
	private String cuitOrigenIng;
	private String glndestinoIng;
	private String cuitDestinoIng;
	private Integer nrOpIng;
	private String respuestaIngreso;
	private String obserIng;
	private Integer codEventoSal;
	private Date fechaSalida;
	private String glnorigenSal;
	private String cuitOrigenSal;
	private String glndestinoSal;
	private String cuitDestinoSal;
	private String respuestaSalida;
	private String obserEgr;
	private Integer nrOpEgr;
	private String nrRemitoPropio;
	private Integer nrTransacSalida;
	private Integer trazaObli;
	private Integer transacNr;
	private String loteStr;
	private String errores;
	private Boolean procesoIngreso;
	private Boolean procesoEgreso;
	private String nroAfiliadoSal;
	private String idObraSocialSal;
	private String erroresSal;
	private String nombrePaciente = "";
	private String obs;
	private String descripC;
	private Long nrTrazabi;
	
	
	
	
	
	@Transient
	public Stock getStockTmp() {
		return stockTmp;
	}


	public void setStockTmp(Stock stockTmp) {
		this.stockTmp = stockTmp;
	}


	public Long getNrTrazabi() {
		return nrTrazabi;
	}


	public void setNrTrazabi(Long nrTrazabi) {
		this.nrTrazabi = nrTrazabi;
	}


	@Transient
	public String getDescripC() {
		String result = "[" + serieGtin + "]|" + gtin + "|" + stock.getDescripC() + "|" + vencimLote;
		descripC = result;
		return descripC;
	}


	public void setDescripC(String descripC) {
		this.descripC = descripC;
	}


	public TrazabiFarma() {
	}
	

	public TrazabiFarma(Integer nr) {
		this.nr = nr;
	}


	@Id
	@Column(name = "nr", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public Integer getNr() {
		return this.nr;
	}

	public void setNr(Integer nr) {
		this.nr = nr;
	}


	@Column(name = "GTIN", length = 14)
	public String getGtin() {
		return this.gtin;
	}

	public void setGtin(String gtin) {
		this.gtin = gtin;
	}

	@Column(name = "SerieGtin", length = 20)
	public String getSerieGtin() {
		return this.serieGtin;
	}

	public void setSerieGtin(String serieGtin) {
		this.serieGtin = serieGtin;
	}

	@Column(name = "cant", precision = 24, scale = 0)
	public Float getCant() {
		return this.cant;
	}

	public void setCant(Float cant) {
		this.cant = cant;
	}

	@Column(name = "exinr")
	public Integer getExinr() {
		return this.exinr;
	}

	public void setExinr(Integer exinr) {
		this.exinr = exinr;
	}

	@Column(name = "nrlote", length = 50)
	public String getNrlote() {
		return this.nrlote;
	}

	public void setNrlote(String nrlote) {
		this.nrlote = nrlote;
	}

	@Column(name = "NrFacCompra", length = 15)
	public String getNrFacCompra() {
		return this.nrFacCompra;
	}

	public void setNrFacCompra(String nrFacCompra) {
		this.nrFacCompra = nrFacCompra;
	}

	@Column(name = "NrRemCompra", length = 15)
	public String getNrRemCompra() {
		return this.nrRemCompra;
	}

	public void setNrRemCompra(String nrRemCompra) {
		this.nrRemCompra = nrRemCompra;
	}

	@Column(name = "GenteNr")
	public Integer getGenteNr() {
		return this.genteNr;
	}

	public void setGenteNr(Integer genteNr) {
		this.genteNr = genteNr;
	}

	@Column(name = "VencimLote", length = 10)
	public String getVencimLote() {
		return this.vencimLote;
	}

	public void setVencimLote(String vencimLote) {
		this.vencimLote = vencimLote;
	}

	@Column(name = "TipoIng")
	public Integer getTipoIng() {
		return this.tipoIng;
	}

	public void setTipoIng(Integer tipoIng) {
		this.tipoIng = tipoIng;
	}

	@Column(name = "TipoSalida")
	public Integer getTipoSalida() {
		return this.tipoSalida;
	}

	public void setTipoSalida(Integer tipoSalida) {
		this.tipoSalida = tipoSalida;
	}

	@Column(name = "Impreso")
	public Integer getImpreso() {
		return this.impreso;
	}

	public void setImpreso(Integer impreso) {
		this.impreso = impreso;
	}

	@Column(name = "unico")
	public Integer getUnico() {
		return this.unico;
	}

	public void setUnico(Integer unico) {
		this.unico = unico;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "CodEventoIng")
	public Integer getCodEventoIng() {
		return this.codEventoIng;
	}

	public void setCodEventoIng(Integer codEventoIng) {
		this.codEventoIng = codEventoIng;
	}

	@Column(name = "FechaIng", length = 16)
	public Date getFechaIng() {
		return this.fechaIng;
	}

	public void setFechaIng(Date fechaIng) {
		this.fechaIng = fechaIng;
	}

	@Column(name = "GLNOrigenIng", length = 20)
	public String getGlnorigenIng() {
		return this.glnorigenIng;
	}

	public void setGlnorigenIng(String glnorigenIng) {
		this.glnorigenIng = glnorigenIng;
	}

	@Column(name = "CuitOrigenIng", length = 15)
	public String getCuitOrigenIng() {
		return this.cuitOrigenIng;
	}

	public void setCuitOrigenIng(String cuitOrigenIng) {
		this.cuitOrigenIng = cuitOrigenIng;
	}

	@Column(name = "GLNDestinoIng", length = 20)
	public String getGlndestinoIng() {
		return this.glndestinoIng;
	}

	public void setGlndestinoIng(String glndestinoIng) {
		this.glndestinoIng = glndestinoIng;
	}

	@Column(name = "CuitDestinoIng", length = 15)
	public String getCuitDestinoIng() {
		return this.cuitDestinoIng;
	}

	public void setCuitDestinoIng(String cuitDestinoIng) {
		this.cuitDestinoIng = cuitDestinoIng;
	}

	@Column(name = "NrOpIng")
	public Integer getNrOpIng() {
		return this.nrOpIng;
	}

	public void setNrOpIng(Integer nrOpIng) {
		this.nrOpIng = nrOpIng;
	}

	@Column(name = "RespuestaIngreso", length = 15)
	public String getRespuestaIngreso() {
		return this.respuestaIngreso;
	}

	public void setRespuestaIngreso(String respuestaIngreso) {
		this.respuestaIngreso = respuestaIngreso;
	}

	@Column(name = "ObserIng", length = 150)
	public String getObserIng() {
		return this.obserIng;
	}

	public void setObserIng(String obserIng) {
		this.obserIng = obserIng;
	}

	@Column(name = "CodEventoSal")
	public Integer getCodEventoSal() {
		return this.codEventoSal;
	}

	public void setCodEventoSal(Integer codEventoSal) {
		this.codEventoSal = codEventoSal;
	}

	@Column(name = "FechaSalida", length = 16)
	public Date getFechaSalida() {
		return this.fechaSalida;
	}

	public void setFechaSalida(Date fechaSalida) {
		this.fechaSalida = fechaSalida;
	}

	@Column(name = "GLNOrigenSal", length = 50)
	public String getGlnorigenSal() {
		return this.glnorigenSal;
	}

	public void setGlnorigenSal(String glnorigenSal) {
		this.glnorigenSal = glnorigenSal;
	}

	@Column(name = "CuitOrigenSal", length = 15)
	public String getCuitOrigenSal() {
		return this.cuitOrigenSal;
	}

	public void setCuitOrigenSal(String cuitOrigenSal) {
		this.cuitOrigenSal = cuitOrigenSal;
	}

	@Column(name = "GLNDestinoSal", length = 20)
	public String getGlndestinoSal() {
		return this.glndestinoSal;
	}

	public void setGlndestinoSal(String glndestinoSal) {
		this.glndestinoSal = glndestinoSal;
	}

	@Column(name = "CuitDestinoSal", length = 15)
	public String getCuitDestinoSal() {
		return this.cuitDestinoSal;
	}

	public void setCuitDestinoSal(String cuitDestinoSal) {
		this.cuitDestinoSal = cuitDestinoSal;
	}

	@Column(name = "RespuestaSalida", length = 15)
	public String getRespuestaSalida() {
		return this.respuestaSalida;
	}

	public void setRespuestaSalida(String respuestaSalida) {
		this.respuestaSalida = respuestaSalida;
	}

	@Column(name = "ObserEgr", length = 150)
	public String getObserEgr() {
		return this.obserEgr;
	}

	public void setObserEgr(String obserEgr) {
		this.obserEgr = obserEgr;
	}

	@Column(name = "NrOpEgr")
	public Integer getNrOpEgr() {
		return this.nrOpEgr;
	}

	public void setNrOpEgr(Integer nrOpEgr) {
		this.nrOpEgr = nrOpEgr;
	}

	@Column(name = "NrRemitoPropio", length = 20)
	public String getNrRemitoPropio() {
		return this.nrRemitoPropio;
	}

	public void setNrRemitoPropio(String nrRemitoPropio) {
		this.nrRemitoPropio = nrRemitoPropio;
	}

	@Column(name = "NrTransacSalida")
	public Integer getNrTransacSalida() {
		return this.nrTransacSalida;
	}

	public void setNrTransacSalida(Integer nrTransacSalida) {
		this.nrTransacSalida = nrTransacSalida;
	}

	@Column(name = "TrazaObli")
	public Integer getTrazaObli() {
		return this.trazaObli;
	}

	public void setTrazaObli(Integer trazaObli) {
		this.trazaObli = trazaObli;
	}

	@OneToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="articulo")
	public Stock getStock() {
		return stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	public Integer getTransacNr() {
		return transacNr;
	}

	public void setTransacNr(Integer transacNr) {
		this.transacNr = transacNr;
	}

	public String getLoteStr() {
		return loteStr;
	}

	public void setLoteStr(String loteStr) {
		this.loteStr = loteStr;
	}

	public String getErrores() {
		return errores;
	}

	public void setErrores(String errores) {
		this.errores = errores;
	}


	public Boolean getProcesoIngreso() {
		return procesoIngreso;
	}


	public void setProcesoIngreso(Boolean procesoIngreso) {
		this.procesoIngreso = procesoIngreso;
	}


	public Boolean getProcesoEgreso() {
		return procesoEgreso;
	}


	public void setProcesoEgreso(Boolean procesoEgreso) {
		this.procesoEgreso = procesoEgreso;
	}


	public String getNroAfiliadoSal() {
		return nroAfiliadoSal;
	}


	public void setNroAfiliadoSal(String nroAfiliadoSal) {
		this.nroAfiliadoSal = nroAfiliadoSal;
	}


	public String getIdObraSocialSal() {
		return idObraSocialSal;
	}


	public void setIdObraSocialSal(String idObraSocialSal) {
		this.idObraSocialSal = idObraSocialSal;
	}


	@Column(name = "erroresSal", length = 255)
	public String getErroresSal() {
		return erroresSal;
	}

	
	public void setErroresSal(String erroresSal) {
		this.erroresSal = erroresSal;
	}


	public String getNombrePaciente() {
		return nombrePaciente;
	}


	public void setNombrePaciente(String nombrePaciente) {
		this.nombrePaciente = nombrePaciente;
	}

	@Column(name = "obs", length = 255)
	public String getObs() {
		return obs;
	}


	public void setObs(String obs) {
		this.obs = obs;
	}


}
